@extends('layouts.public')

@section('title', $edition->title.' - '.$account->name)
@section('publicFooter')<x-ui.powered-footer :account="$account" :show-locale-switcher="true" class="mx-auto max-w-6xl bg-canvas px-5 pb-8 sm:px-8" />@endsection

@section('content')
@php($cover = $edition->media->firstWhere('is_cover', true))
<main class="min-h-screen bg-canvas text-slate-950"><section class="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><x-ui.public-studio-header :account="$account" />
    <header class="mt-8 overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-crm">@if($cover?->url())<img src="{{ $cover->url() }}" alt="{{ $cover->alt_text ?: $edition->title }}" class="max-h-[32rem] w-full object-cover">@endif<div class="grid gap-8 p-6 sm:p-10 lg:grid-cols-[1fr_21rem]"><div><p class="text-sm font-semibold text-brand-700">{{ $edition->series->name }}</p><h1 class="mt-2 text-4xl font-semibold leading-tight sm:text-6xl">{{ $edition->title }}</h1>@if($edition->summary)<p class="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{{ $edition->summary }}</p>@endif<div class="mt-6 flex flex-wrap gap-2"><x-ui.button :href="route('festival.login', $account->slug)">{{ __('app.festival_portal_open') }}</x-ui.button><x-ui.button :href="route('public.festivals.index', $account->slug)" variant="secondary">{{ __('app.all_festivals') }}</x-ui.button></div></div><aside class="rounded-2xl bg-brand-50 p-5 text-brand-950"><strong class="text-xl">{{ $edition->starts_at->timezone($edition->timezone)->format('d.m.Y') }}</strong><p class="mt-1 text-lg">{{ $edition->starts_at->timezone($edition->timezone)->format('H:i') }}–{{ $edition->ends_at->timezone($edition->timezone)->format('H:i') }}</p><p class="mt-4 text-sm leading-6">{{ $edition->venue_name }}<br>{{ $edition->venue_address }}</p>@if($edition->venue_map_url)<a href="{{ $edition->venue_map_url }}" target="_blank" rel="noopener noreferrer" class="mt-3 inline-block text-sm font-semibold underline">{{ __('app.open_map') }}</a>@endif</aside></div></header>
    <div class="mt-8 grid gap-8 lg:grid-cols-[1fr_23rem]"><div class="space-y-6">@if($edition->description_html)<article class="prose prose-slate max-w-none rounded-2xl border border-stone-200 bg-white p-6 shadow-crm sm:p-8">{!! $edition->description_html !!}</article>@endif @foreach($edition->sections as $section)<article class="rounded-2xl border border-stone-200 bg-white p-6 shadow-crm"><h2 class="text-2xl font-semibold">{{ $section->title }}</h2><div class="prose prose-slate mt-4 max-w-none">{!! $section->body_html !!}</div></article>@endforeach @if($edition->rules_html)<article class="rounded-2xl border border-stone-200 bg-white p-6 shadow-crm"><h2 class="text-2xl font-semibold">{{ __('app.festival_rules') }}</h2><div class="prose prose-slate mt-4 max-w-none">{!! $edition->rules_html !!}</div></article>@endif
        @if($edition->results->isNotEmpty())<section class="rounded-2xl border border-stone-200 bg-white p-6 shadow-crm"><h2 class="text-2xl font-semibold">{{ __('app.festival_results') }}</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="px-3 py-2 text-left">#</th><th class="px-3 py-2 text-left">{{ __('app.performance') }}</th><th class="px-3 py-2 text-left">{{ __('app.festival_category') }}</th><th class="px-3 py-2 text-right">{{ __('app.festival_score') }}</th></tr></thead><tbody>@foreach($edition->results->sortBy('rank') as $result)<tr class="border-t border-stone-100"><td class="px-3 py-3 font-semibold">{{ $result->rank }}</td><td class="px-3 py-3">{{ $result->entry->entry_name }}</td><td class="px-3 py-3">{{ $result->entry->category->name }}</td><td class="px-3 py-3 text-right">{{ $result->total_score }}</td></tr>@endforeach</tbody></table></div></section>@endif</div>
        <aside class="lg:sticky lg:top-6 lg:self-start"><form method="POST" action="{{ route('public.festivals.admission.store', [$account->slug, $edition->slug]) }}" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-crm">@csrf<h2 class="text-2xl font-semibold">{{ __('app.festival_admission') }}</h2>@if($errors->any())<div class="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-900"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<div class="mt-4 space-y-3">@forelse($edition->admissionTypes as $type)@php($price = $type->currentPrice())<label class="grid grid-cols-[1fr_5rem] gap-3 rounded-xl border border-stone-200 p-4"><span><strong class="block">{{ $type->name }}</strong><span class="text-sm text-slate-500">{{ number_format($price['price_cents']/100, 2) }} {{ $edition->currency }} · {{ $type->remainingQuantity() }} {{ __('app.left') }}</span></span><span><input type="hidden" name="items[{{ $type->id }}][admission_type_id]" value="{{ $type->id }}"><input type="number" name="items[{{ $type->id }}][quantity]" min="0" max="{{ min($type->max_per_order, $type->remainingQuantity()) }}" value="0" class="crm-field text-center"></span></label>@empty<p class="text-sm text-slate-500">{{ __('app.festival_admission_unavailable') }}</p>@endforelse</div>
            @if($edition->admissionTypes->isNotEmpty() && $providers->isNotEmpty())<div class="mt-4 space-y-3"><input name="buyer_name" required placeholder="{{ __('app.person_name') }}" class="crm-field"><input type="email" name="buyer_email" required placeholder="{{ __('app.email') }}" class="crm-field"><input name="buyer_phone" placeholder="{{ __('app.phone_optional') }}" class="crm-field">@foreach($providers as $provider)<label class="flex items-center gap-3 rounded-xl border border-stone-200 p-3"><input type="radio" name="provider" value="{{ $provider->provider->value }}" @checked($loop->first) class="crm-radio"><x-ui.payment-brand :provider="$provider->provider->value" :label="config('integrations.providers.'.$provider->provider->value.'.label')" /></label>@endforeach<label class="flex items-start gap-2 text-sm text-slate-600"><input type="checkbox" name="terms" value="1" required class="crm-checkbox mt-0.5">{{ __('app.festival_admission_terms') }}</label><x-ui.button type="submit" class="w-full">{{ __('app.pay') }}</x-ui.button></div>@endif</form></aside>
    </div>
</section></main>
@endsection
