@extends('layouts.public')

@section('title', __('app.festival_performance').' - '.$edition->title)

@section('content')
<main class="min-h-screen bg-canvas px-5 py-8"><div class="mx-auto max-w-4xl">@include('festivals.portal._nav')<header class="mt-8"><p class="text-sm font-semibold text-brand-700">{{ $edition->title }}</p><h1 class="mt-1 text-4xl font-semibold">{{ $entry->exists ? __('app.festival_edit_performance') : __('app.festival_new_performance') }}</h1></header>@if($errors->any())<div class="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-900"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $entry->exists ? route('festival.portal.entries.update', [$account->slug, $entry]) : route('festival.portal.entries.store', [$account->slug, $edition->slug]) }}" class="mt-6 space-y-6">@csrf @if($entry->exists) @method('PUT') @endif
        <section class="rounded-2xl border border-stone-200 bg-white p-6 shadow-crm"><h2 class="text-xl font-semibold">{{ __('app.festival_performance_details') }}</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><label><span class="crm-label">{{ __('app.festival_category') }}</span><select name="festival_category_id" required class="crm-field"><option value="">{{ __('app.select') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('festival_category_id', $entry->festival_category_id) === $category->id)>{{ $category->name }} · {{ $category->min_members }}–{{ $category->max_members }}</option>@endforeach</select></label><label><span class="crm-label">{{ __('app.festival_performer_name') }}</span><input name="performer_name" value="{{ old('performer_name', $entry->performer_name) }}" required class="crm-field"></label><label><span class="crm-label">{{ __('app.festival_act_title') }}</span><input name="act_title" value="{{ old('act_title', $entry->act_title) }}" class="crm-field"></label><label class="sm:col-span-2"><span class="crm-label">{{ __('app.description') }}</span><textarea name="act_description" rows="4" class="crm-field">{{ old('act_description', $entry->act_description) }}</textarea></label></div></section>
        <section class="rounded-2xl border border-stone-200 bg-white p-6 shadow-crm"><h2 class="text-xl font-semibold">{{ __('app.festival_roster') }}</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($participants as $participant)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-stone-200 p-4 has-checked:border-brand-500 has-checked:bg-brand-50"><input type="checkbox" name="participant_ids[]" value="{{ $participant->id }}" @checked(collect(old('participant_ids', $entry->exists ? $entry->participants->modelKeys() : []))->contains($participant->id)) class="crm-checkbox"><span><strong class="block">{{ $participant->displayName() }}</strong><span class="text-xs text-slate-500">{{ $participant->date_of_birth->format('d.m.Y') }}</span></span></label>@empty<p class="sm:col-span-2 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{{ __('app.festival_participants_required') }}</p>@endforelse</div></section>
        <div class="flex justify-end"><x-ui.button type="submit" size="lg">{{ __('app.save_draft') }}</x-ui.button></div>
    </form>
</div></main>
@endsection
