@extends('layouts.festival-portal')

@section('title', __('app.festival_portal_my_team').' - '.$account->name)

@section('content')
<main class="min-h-screen bg-canvas px-4 py-6 sm:px-5 sm:py-8"><div class="mx-auto max-w-6xl">@include('festivals.portal._nav')<header class="mt-8"><h1 class="text-3xl font-semibold sm:text-4xl">{{ __('app.festival_portal_my_team') }}</h1><p class="mt-2 text-slate-600">{{ __('app.festival_portal_team_copy') }}</p></header>@if(session('status'))<div class="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</div>@endif
    <div class="mt-6 grid gap-5 lg:grid-cols-[1fr_23rem]"><section class="space-y-3">@forelse($participants as $participant)<details class="rounded-2xl border border-stone-200 bg-white p-5 shadow-crm"><summary class="cursor-pointer font-semibold">{{ $participant->displayName() }} <span class="ml-2 text-sm font-normal text-slate-500">{{ $participant->date_of_birth->format('d.m.Y') }}</span></summary>@if($participant->is_profile_owner)<p class="mt-4 text-sm text-slate-600">{{ __('app.festival_profile') }}</p><a href="{{ route('festival.portal.profile.edit', $account->slug) }}" class="mt-2 inline-flex text-sm font-semibold text-brand-700">{{ __('app.edit_profile') }}</a>@else<form method="POST" action="{{ route('festival.portal.participants.update', [$account->slug, $participant]) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input name="first_name" value="{{ $participant->first_name }}" required class="crm-field"><input name="last_name" value="{{ $participant->last_name }}" required class="crm-field"><input name="patronymic" value="{{ $participant->patronymic }}" class="crm-field"><input type="date" name="date_of_birth" value="{{ $participant->date_of_birth->format('Y-m-d') }}" required class="crm-field"><textarea name="notes" class="crm-field sm:col-span-2">{{ $participant->notes }}</textarea><x-ui.button type="submit">{{ __('app.save') }}</x-ui.button></form><form method="POST" action="{{ route('festival.portal.participants.destroy', [$account->slug, $participant]) }}" class="mt-3">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">{{ __('app.festival_portal_remove_from_team') }}</button></form>@endif</details>@empty<x-ui.empty-state icon="users">{{ __('app.festival_portal_team_empty') }}</x-ui.empty-state>@endforelse</section>
        <aside><form method="POST" action="{{ route('festival.portal.participants.store', $account->slug) }}" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-crm">@csrf<h2 class="text-xl font-semibold">{{ __('app.festival_portal_add_to_team') }}</h2><div class="mt-4 space-y-3"><input name="first_name" required placeholder="{{ __('app.first_name') }}" class="crm-field"><input name="last_name" required placeholder="{{ __('app.last_name') }}" class="crm-field"><input name="patronymic" placeholder="{{ __('app.patronymic') }}" class="crm-field"><label><span class="crm-label">{{ __('app.date_of_birth') }}</span><input type="date" name="date_of_birth" required class="crm-field"></label><textarea name="notes" rows="3" placeholder="{{ __('app.notes') }}" class="crm-field"></textarea><x-ui.button type="submit" class="w-full">{{ __('app.festival_portal_add_to_team') }}</x-ui.button></div></form></aside>
    </div>
</div></main>
@endsection
