<?php

return [
    'copy' => [
        'en' => [
            'title' => 'Ladna changelog',
            'current_version' => 'Current version :version',
            'heading' => "What's new in Ladna",
            'language_label' => 'Language',
            'history_label' => 'Release history',
        ],
        'uk' => [
            'title' => 'Журнал змін Ladna',
            'current_version' => 'Поточна версія :version',
            'heading' => 'Що нового в Ladna',
            'language_label' => 'Мова',
            'history_label' => 'Історія релізів',
        ],
    ],
    'releases' => [
        'en' => [
            [
                'version' => '0.28.0',
                'date' => '2026-06-24',
                'title' => 'Studio rules and purchase agreement',
                'items' => ['Added a Studio rules tab with a rich HTML editor, a branded public rules page for each studio, class-pass checkout agreement validation, public rules links, and updated owner help documentation.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.27.0',
                'date' => '2026-06-24',
                'title' => 'Public studio owner help',
                'items' => ['Added a public Ukrainian help section for studio owners with plain-language guides, desktop screenshots, footer access, and a dedicated Ladna help-update skill for keeping future feature documentation current.'],
                'meta' => 'Release commit pending.',
            ],
            [
                'version' => '0.26.0',
                'date' => '2026-06-24',
                'title' => 'Public class pass checkout',
                'items' => ['Added public class-pass purchase links with customer login/profile return flow, payment attempt history, branded provider buttons, and Monopay, LiqPay, and WayForPay callback handling that issues real customer passes only after verified successful payment.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.25.0',
                'date' => '2026-06-24',
                'title' => 'QR links and print poster',
                'items' => ['Renamed the QR tab to QR codes and links, added public schedule, price, and embed links for active studio locations, and redesigned QR printing into a centered branded poster.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.24.0',
                'date' => '2026-06-24',
                'title' => 'Role-focused studio dashboards',
                'items' => ['Reworked the main studio page into an operational owner dashboard with live classes, passes, customers, leads, and load by location and hall, while trainer logins now see their own agenda for today, tomorrow, and the rest of the week.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.23.1',
                'date' => '2026-06-24',
                'title' => 'Mobile quick booking labels',
                'items' => ['Removed duplicate plus signs from mobile quick booking button labels while keeping the icon and short action text.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.23.0',
                'date' => '2026-06-24',
                'title' => 'Opening hours and quick booking availability',
                'items' => ['Added account opening hours in My Brand and made quick private lesson and room rental booking show only available account-local time slots, with room and trainer conflict checks.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.22.4',
                'date' => '2026-06-24',
                'title' => 'Account timezone lead timestamps',
                'items' => ['Returned website lead API and admin creation times in the studio account timezone and added regression coverage for non-UTC group-class availability and same-day past grouping.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.22.3',
                'date' => '2026-06-24',
                'title' => 'Website lead list polish',
                'items' => ['Removed the API token shortcut from website leads and added clearer spacing between status controls and quick-booking actions.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.22.2',
                'date' => '2026-06-24',
                'title' => 'Website lead cleanup controls',
                'items' => ['Shortened website lead quick-booking buttons, switched them to the primary brand color, and added guarded lead deletion for cleanup of test submissions.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.22.1',
                'date' => '2026-06-24',
                'title' => 'Release metadata cleanup',
                'items' => ['Recorded the 0.22.0 release commit in the public changelog and added coverage for the internal login remember-me cookie lifetime.'],
                'meta' => 'Release maintenance commit.',
            ],
            [
                'version' => '0.22.0',
                'date' => '2026-06-24',
                'title' => 'Quick bookings and website leads',
                'items' => ['Added shared quick booking flows for group classes, private lessons, and room rentals, introduced website lead intake with account bearer tokens, lead status management, OpenAPI documentation, and responsive admin modal improvements.'],
                'meta' => 'Commit 60b3513.',
            ],
            [
                'version' => '0.21.1',
                'date' => '2026-06-23',
                'title' => 'Migration schema baseline',
                'items' => ['Squashed the applied migration history into a committed MySQL schema dump, removed historical data/backfill migrations from new-environment setup, and aligned local bootstrap documentation with the schema dump workflow.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.21.0',
                'date' => '2026-06-23',
                'title' => 'Class pass format binding',
                'items' => ['Added an explicit class format to class passes and prices, filtered available class formats in the form by that selection, and made pricing tabs use the pass format directly.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.20.0',
                'date' => '2026-06-23',
                'title' => 'Class format architecture',
                'items' => ['Separated group classes, private lessons, and room rentals into clearer studio workflows with format tabs, configurable format colors, combined calendar color accents, class-pass pricing tabs, manual calendar slots for non-recurring services, and refreshed Charmpole demo catalog content.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.19.0',
                'date' => '2026-06-23',
                'title' => 'Compact list actions',
                'items' => ['Replaced wide row action buttons in entity lists with compact icon-only controls for copy, edit, delete, schedule, embed, and related quick actions while keeping hover titles and accessible labels.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.18.0',
                'date' => '2026-06-23',
                'title' => 'Trainer workspace and faster setup',
                'items' => ['Hid unavailable trainer menu items, showed trainer levels in the account header, added a color picker to class format editing, and added copy actions for directions, class formats, and class passes.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.17.0',
                'date' => '2026-06-23',
                'title' => 'Customer login and portal',
                'items' => ['Added branded studio customer login pages, email/password, OTP, and Google OAuth configuration, Turnstile protection, 90-day customer sessions, phone masks, customer profile completion, password changes, QR login links, and the first customer portal views for passes, visits, and profile management.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.16.0',
                'date' => '2026-06-21',
                'title' => 'Public legal pages',
                'items' => ['Added public Terms of Service and Privacy Policy pages in English and Ukrainian, with localized footer links for Google Developer Console readiness.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.15.0',
                'date' => '2026-06-21',
                'title' => 'Production deployment workflow',
                'items' => ['Added a guarded Ladna production deploy skill with dry-run checks, production SSH handoff, locked dependency install, Vite build, forced migrations without seeders, cache optimization, queue restart, and maintenance-mode cleanup.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.14.0',
                'date' => '2026-06-21',
                'title' => 'Studio class pass lifecycle',
                'items' => [
                    'Added purchased customer class passes with unique codes, reservation and attendance ledger, manual issue flow, active pass management, customer pass history, booking pass alerts, normalization command, public price page, embeddable price API, and Charmpole demo pricing for group classes, private lessons, rentals, and trial passes.',
                ],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.13.0',
                'date' => '2026-06-20',
                'title' => 'Async scheduled class booking management',
                'items' => ['Made scheduled class booking create, status update, and delete actions save without a full page reload, moved older same-day classes behind a collapsible history block, and added a reusable ajaxable-forms skill for future opt-in form work.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.12.0',
                'date' => '2026-06-20',
                'title' => 'Versioning and changelog foundation',
                'items' => ['Added the root VERSION file, bilingual Laravel changelog pages, footer version output, and a release workflow skill.'],
                'meta' => 'Versioning system release.',
            ],
            [
                'version' => '0.11.0',
                'date' => '2026-06-20',
                'title' => 'Direction colors in the class timeline',
                'items' => ['Added activity direction color handling and surfaced those colors in the scheduled class timeline.'],
                'meta' => 'Commit a800d35.',
            ],
            [
                'version' => '0.10.1',
                'date' => '2026-06-20',
                'title' => 'Dependency audit maintenance',
                'items' => ['Updated the lockfile with npm audit fixes.'],
                'meta' => 'Commit df51a9a.',
            ],
            [
                'version' => '0.10.0',
                'date' => '2026-06-20',
                'title' => 'Scheduled class timeline filters',
                'items' => ['Added timeline filters for generated classes and covered the filtering behavior with feature tests.'],
                'meta' => 'Commit cadc37f.',
            ],
            [
                'version' => '0.9.0',
                'date' => '2026-06-20',
                'title' => 'Scheduled class and slug handling refactor',
                'items' => ['Refined schedule class management, customer search, slug generation, locale handling, and related tests.'],
                'meta' => 'Commit 48ce0d1.',
            ],
            [
                'version' => '0.8.0',
                'date' => '2026-06-20',
                'title' => 'Studio owner navigation',
                'items' => ['Reworked studio owner navigation, brand settings, owner profile entry points, and account-scoped settings flow.'],
                'meta' => 'Commit 0224419.',
            ],
            [
                'version' => '0.7.1',
                'date' => '2026-06-20',
                'title' => 'Unreadable integration credentials recovery',
                'items' => ['Handled saved integration secrets that cannot be decrypted and prompted users to re-enter them safely.'],
                'meta' => 'Commit 078ee51.',
            ],
            [
                'version' => '0.7.0',
                'date' => '2026-06-19',
                'title' => 'Class pass pricing UX',
                'items' => ['Improved class pass pricing controls, validation, any-time add-on behavior, and test coverage.'],
                'meta' => 'Commit a434d1f.',
            ],
            [
                'version' => '0.6.0',
                'date' => '2026-06-19',
                'title' => 'Platform account profile settings',
                'items' => ['Added platform admin profile management and shared profile update handling.'],
                'meta' => 'Commit 54ce3c8.',
            ],
            [
                'version' => '0.5.0',
                'date' => '2026-06-19',
                'title' => 'Owner profile settings and Ladna guidance',
                'items' => ['Added studio owner profile settings and renamed the domain guidance from Charm CRM to Ladna.'],
                'meta' => 'Commit 89d6937.',
            ],
            [
                'version' => '0.4.1',
                'date' => '2026-06-19',
                'title' => 'Sanitized README restored',
                'items' => ['Restored a clean README and adjusted the example environment file.'],
                'meta' => 'Commit f48b3fa.',
            ],
            [
                'version' => '0.4.0',
                'date' => '2026-06-19',
                'title' => 'Ladna repository preparation',
                'items' => ['Prepared the Ladna-branded app shell, system appearance settings, trainer levels, brand assets, and supporting tests.'],
                'meta' => 'Commit e992c68.',
            ],
            [
                'version' => '0.3.0',
                'date' => '2026-06-17',
                'title' => 'Integration settings',
                'items' => ['Added platform and studio integration configuration, provider catalog metadata, and settings tests.'],
                'meta' => 'Commit c3d3865.',
            ],
            [
                'version' => '0.2.0',
                'date' => '2026-06-17',
                'title' => 'CRM domain roles and studio flows',
                'items' => ['Introduced studio roles, permissions, customers, class passes, bookings, trainers, subscriptions, and domain tests.'],
                'meta' => 'Commit ee60fe2.',
            ],
            [
                'version' => '0.1.0',
                'date' => '2026-06-16',
                'title' => 'Initial application baseline',
                'items' => ['Created the Laravel application baseline with Ladna scheduling, accounts, public schedule, tests, local agent guidance, and frontend assets.'],
                'meta' => 'Commit b9f0de6.',
            ],
        ],
        'uk' => [
            [
                'version' => '0.28.0',
                'date' => '2026-06-24',
                'title' => 'Правила студії та згода під час купівлі',
                'items' => ['Додано вкладку Правила студії з HTML-редактором, брендовану публічну сторінку правил для кожної студії, перевірку згоди під час купівлі абонемента, посилання на правила на публічних сторінках і оновлену допомогу для власниць.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.27.0',
                'date' => '2026-06-24',
                'title' => 'Публічна допомога для власниць студій',
                'items' => ['Додано публічний україномовний розділ допомоги для власниць студій з простими інструкціями, скріншотами desktop-екранів, посиланням у футері та окремим skill для майбутнього оновлення хелпа.'],
                'meta' => 'Релізний коміт очікується.',
            ],
            [
                'version' => '0.26.0',
                'date' => '2026-06-24',
                'title' => 'Публічна купівля абонементів',
                'items' => ['Додано публічні посилання купівлі абонементів з поверненням після входу та доповнення профілю клієнта, історію спроб оплати, брендовані кнопки провайдерів і callback-обробку Monopay, LiqPay та WayForPay, яка видає реальний абонемент тільки після перевіреної успішної оплати.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.25.0',
                'date' => '2026-06-24',
                'title' => 'QR-посилання та постер для друку',
                'items' => ['Перейменовано вкладку QR на QR-коди та посилання, додано публічні посилання на розклад, прайс і embed для активних локацій студії та перероблено друк QR у центрований брендований постер.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.24.0',
                'date' => '2026-06-24',
                'title' => 'Рольові дашборди студії',
                'items' => ['Перероблено головну сторінку студії в операційний дашборд власника з живими заняттями, абонементами, клієнтами, заявками та завантаженням за локаціями і залами, а тренери тепер бачать власний розклад на сьогодні, завтра і решту тижня.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.23.1',
                'date' => '2026-06-24',
                'title' => 'Мобільні підписи швидкого запису',
                'items' => ['Прибрано дубльовані плюси з мобільних кнопок швидкого запису, залишивши іконку та коротку назву дії.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.23.0',
                'date' => '2026-06-24',
                'title' => 'Графік роботи та доступний час швидкого запису',
                'items' => ['Додано графік роботи акаунта в Мій бренд і зроблено швидкий запис на індивідуальні заняття та оренду через доступні локальні слоти з перевіркою конфліктів залу й тренера.'],
                'meta' => 'Релізний комміт.',
            ],
            [
                'version' => '0.22.4',
                'date' => '2026-06-24',
                'title' => 'Час заявок у часовому поясі акаунта',
                'items' => ['Повертаємо час створення заявок з сайту в API та адмінці у часовому поясі студійного акаунта й додали regression-покриття для групових занять у не-UTC часових поясах.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.22.3',
                'date' => '2026-06-24',
                'title' => 'Полірування списку заявок',
                'items' => ['Прибрано посилання на API токени зі сторінки заявок і додано чіткіший відступ між зміною статусу та швидкими діями запису.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.22.2',
                'date' => '2026-06-24',
                'title' => 'Очищення заявок з сайту',
                'items' => ['Скорочено кнопки швидкого запису в заявках з сайту, переведено їх на основний фіолетовий колір і додано захищене видалення заявок для очищення тестових відправок.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.22.1',
                'date' => '2026-06-24',
                'title' => 'Очищення метаданих релізу',
                'items' => ['Записано коміт релізу 0.22.0 у публічному changelog та додано покриття для lifetime remember-me cookie внутрішнього входу.'],
                'meta' => 'Maintenance-коміт релізу.',
            ],
            [
                'version' => '0.22.0',
                'date' => '2026-06-24',
                'title' => 'Швидкі записи і заявки з сайту',
                'items' => ['Додано спільні сценарії швидкого запису на групові заняття, індивідуальні заняття та оренду, заявки з сайту з bearer tokens акаунта, керування статусами заявок, OpenAPI-документацію та покращені responsive модальні вікна в адмінці.'],
                'meta' => 'Коміт 60b3513.',
            ],
            [
                'version' => '0.21.1',
                'date' => '2026-06-23',
                'title' => 'Базова схема міграцій',
                'items' => ['Згорнуто застосовану історію міграцій у закомічений MySQL schema dump, прибрано історичні data/backfill міграції з налаштування нових середовищ та узгоджено локальний bootstrap з роботою через schema dump.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.21.0',
                'date' => '2026-06-23',
                'title' => 'Прив’язка формату до абонементу',
                'items' => ['Додано явний формат до абонементів і цін, відфільтровано доступні формати занять у формі за вибором та переведено вкладки прайсу на формат самого абонемента.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.20.0',
                'date' => '2026-06-23',
                'title' => 'Архітектура форматів занять',
                'items' => ['Розділено групові заняття, індивідуальні заняття та оренду на зрозуміліші студійні сценарії з вкладками форматів, налаштуванням кольорів форматів, комбінованими кольоровими акцентами в календарі, вкладками для абонементів і цін, ручними слотами календаря для нерегулярних послуг та оновленим demo-каталогом Charmpole.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.19.0',
                'date' => '2026-06-23',
                'title' => 'Компактні дії у списках',
                'items' => ['Замінено широкі кнопки дій у списках сутностей на компактні іконки для копіювання, редагування, видалення, розкладу, embed та повʼязаних швидких дій зі збереженням підказок і доступних підписів.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.18.0',
                'date' => '2026-06-23',
                'title' => 'Робочий простір тренера і швидше налаштування',
                'items' => ['Приховано недоступні пункти меню для тренера, показано рівень тренера у верхньому блоці акаунта, додано вибір кольору в редагуванні форматів занять і копіювання для напрямів, форматів занять та абонементів.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.17.0',
                'date' => '2026-06-23',
                'title' => 'Клієнтський вхід і кабінет',
                'items' => ['Додано брендовані сторінки клієнтського входу для студій, налаштування email/password, OTP і Google OAuth, захист Turnstile, 90-денні клієнтські сесії, маски телефону, обовʼязкове доповнення профілю, зміну пароля, QR-посилання для входу та перші екрани клієнтського кабінету з абонементами, відвідуваннями й профілем.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.16.0',
                'date' => '2026-06-21',
                'title' => 'Публічні юридичні сторінки',
                'items' => ['Додано публічні сторінки Угоди користувача та Політики конфіденційності українською й англійською мовами, а також локалізовані посилання у футері для підготовки Google Developer Console.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.15.0',
                'date' => '2026-06-21',
                'title' => 'Production deployment workflow',
                'items' => ['Додано guarded skill для production deploy Ladna з dry-run перевірками, production SSH handoff, встановленням locked залежностей, Vite build, forced migrations без seeders, оптимізацією кешів, restart queue та cleanup maintenance mode.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.14.0',
                'date' => '2026-06-21',
                'title' => 'Життєвий цикл студійних абонементів',
                'items' => [
                    'Додано куплені клієнтські абонементи з унікальними кодами, ledger резервів і відвідувань, ручну видачу, керування активними абонементами, історію в картці клієнта, попередження в записах без відповідного абонемента, команду нормалізації, публічну сторінку цін, embeddable price API та demo-ціни Charmpole для групових занять, індивідуальних занять, оренди й пробних занять.',
                ],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.13.0',
                'date' => '2026-06-20',
                'title' => 'Асинхронне керування записами на заняття',
                'items' => ['Зроблено додавання, зміну статусу й видалення записів у керуванні заняттями без повного перезавантаження сторінки, перенесено старі заняття поточного дня в згортуваний блок історії та додано reusable ajaxable-forms skill для майбутніх форм.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.12.0',
                'date' => '2026-06-20',
                'title' => 'Основа версіонування та журналу змін',
                'items' => ['Додано кореневий файл VERSION, сторінки журналу змін двома мовами в Laravel, версію у футері та skill для релізного процесу.'],
                'meta' => 'Реліз системи версіонування.',
            ],
            [
                'version' => '0.11.0',
                'date' => '2026-06-20',
                'title' => 'Кольори напрямів у таймлайні занять',
                'items' => ['Додано обробку кольорів напрямів активності та показ цих кольорів у таймлайні занять.'],
                'meta' => 'Коміт a800d35.',
            ],
            [
                'version' => '0.10.1',
                'date' => '2026-06-20',
                'title' => 'Технічне оновлення залежностей',
                'items' => ['Оновлено lockfile після npm audit fix.'],
                'meta' => 'Коміт df51a9a.',
            ],
            [
                'version' => '0.10.0',
                'date' => '2026-06-20',
                'title' => 'Фільтри таймлайна занять',
                'items' => ['Додано фільтри для згенерованих занять і покрито поведінку фільтрації feature-тестами.'],
                'meta' => 'Коміт cadc37f.',
            ],
            [
                'version' => '0.9.0',
                'date' => '2026-06-20',
                'title' => 'Рефакторинг занять і slug-логіки',
                'items' => ['Уточнено керування заняттями, пошук клієнтів, генерацію slug, локаль і повʼязані тести.'],
                'meta' => 'Коміт 48ce0d1.',
            ],
            [
                'version' => '0.8.0',
                'date' => '2026-06-20',
                'title' => 'Навігація власника студії',
                'items' => ['Перероблено навігацію власника студії, налаштування бренду, профіль власника та account-scoped налаштування.'],
                'meta' => 'Коміт 0224419.',
            ],
            [
                'version' => '0.7.1',
                'date' => '2026-06-20',
                'title' => 'Відновлення недоступних інтеграційних даних',
                'items' => ['Оброблено збережені інтеграційні секрети, які неможливо розшифрувати, і додано безпечний запит на повторне введення.'],
                'meta' => 'Коміт 078ee51.',
            ],
            [
                'version' => '0.7.0',
                'date' => '2026-06-19',
                'title' => 'UX цін абонементів',
                'items' => ['Покращено керування цінами абонементів, валідацію, поведінку any-time add-on і тестове покриття.'],
                'meta' => 'Коміт a434d1f.',
            ],
            [
                'version' => '0.6.0',
                'date' => '2026-06-19',
                'title' => 'Профіль адміністратора платформи',
                'items' => ['Додано керування профілем адміністратора платформи та спільну дію оновлення профілю.'],
                'meta' => 'Коміт 54ce3c8.',
            ],
            [
                'version' => '0.5.0',
                'date' => '2026-06-19',
                'title' => 'Профіль власника та Ladna guidance',
                'items' => ['Додано налаштування профілю власника студії та перейменовано доменні інструкції з Charm CRM на Ladna.'],
                'meta' => 'Коміт 89d6937.',
            ],
            [
                'version' => '0.4.1',
                'date' => '2026-06-19',
                'title' => 'Відновлено очищений README',
                'items' => ['Відновлено чистий README та скориговано приклад environment-файлу.'],
                'meta' => 'Коміт f48b3fa.',
            ],
            [
                'version' => '0.4.0',
                'date' => '2026-06-19',
                'title' => 'Підготовка репозиторію Ladna',
                'items' => ['Підготовлено брендований app shell Ladna, системні налаштування вигляду, рівні тренерів, бренд-ресурси та тести.'],
                'meta' => 'Коміт e992c68.',
            ],
            [
                'version' => '0.3.0',
                'date' => '2026-06-17',
                'title' => 'Налаштування інтеграцій',
                'items' => ['Додано налаштування інтеграцій для платформи й студії, каталог провайдерів і тести налаштувань.'],
                'meta' => 'Коміт c3d3865.',
            ],
            [
                'version' => '0.2.0',
                'date' => '2026-06-17',
                'title' => 'CRM ролі та студійні процеси',
                'items' => ['Додано ролі студії, permissions, клієнтів, абонементи, записи, тренерів, тарифи та доменні тести.'],
                'meta' => 'Коміт ee60fe2.',
            ],
            [
                'version' => '0.1.0',
                'date' => '2026-06-16',
                'title' => 'Початкова база застосунку',
                'items' => ['Створено базовий Laravel-застосунок із розкладом Ladna, акаунтами, публічним розкладом, тестами, локальними agent-інструкціями та frontend-ресурсами.'],
                'meta' => 'Коміт b9f0de6.',
            ],
        ],
    ],
];
