<?php

return [
    'copy' => [
        'en' => [
            'title' => 'Ladna changelog',
            'current_version' => 'Current version :version',
            'heading' => "What's new in Ladna",
            'language_label' => 'Language',
            'history_label' => 'Release history',
        ],
        'uk' => [
            'title' => 'Журнал змін Ladna',
            'current_version' => 'Поточна версія :version',
            'heading' => 'Що нового в Ladna',
            'language_label' => 'Мова',
            'history_label' => 'Історія релізів',
        ],
    ],
    'releases' => [
        'en' => [
            [
                'version' => '0.17.0',
                'date' => '2026-06-23',
                'title' => 'Customer login and portal',
                'items' => ['Added branded studio customer login pages, email/password, OTP, and Google OAuth configuration, Turnstile protection, 90-day customer sessions, phone masks, customer profile completion, password changes, QR login links, and the first customer portal views for passes, visits, and profile management.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.16.0',
                'date' => '2026-06-21',
                'title' => 'Public legal pages',
                'items' => ['Added public Terms of Service and Privacy Policy pages in English and Ukrainian, with localized footer links for Google Developer Console readiness.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.15.0',
                'date' => '2026-06-21',
                'title' => 'Production deployment workflow',
                'items' => ['Added a guarded Ladna production deploy skill with dry-run checks, production SSH handoff, locked dependency install, Vite build, forced migrations without seeders, cache optimization, queue restart, and maintenance-mode cleanup.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.14.0',
                'date' => '2026-06-21',
                'title' => 'Studio class pass lifecycle',
                'items' => [
                    'Added purchased customer class passes with unique codes, reservation and attendance ledger, manual issue flow, active pass management, customer pass history, booking pass alerts, normalization command, public price page, embeddable price API, and Charmpole demo pricing for group classes, private lessons, rentals, and trial passes.',
                ],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.13.0',
                'date' => '2026-06-20',
                'title' => 'Async scheduled class booking management',
                'items' => ['Made scheduled class booking create, status update, and delete actions save without a full page reload, moved older same-day classes behind a collapsible history block, and added a reusable ajaxable-forms skill for future opt-in form work.'],
                'meta' => 'Release commit.',
            ],
            [
                'version' => '0.12.0',
                'date' => '2026-06-20',
                'title' => 'Versioning and changelog foundation',
                'items' => ['Added the root VERSION file, bilingual Laravel changelog pages, footer version output, and a release workflow skill.'],
                'meta' => 'Versioning system release.',
            ],
            [
                'version' => '0.11.0',
                'date' => '2026-06-20',
                'title' => 'Direction colors in the class timeline',
                'items' => ['Added activity direction color handling and surfaced those colors in the scheduled class timeline.'],
                'meta' => 'Commit a800d35.',
            ],
            [
                'version' => '0.10.1',
                'date' => '2026-06-20',
                'title' => 'Dependency audit maintenance',
                'items' => ['Updated the lockfile with npm audit fixes.'],
                'meta' => 'Commit df51a9a.',
            ],
            [
                'version' => '0.10.0',
                'date' => '2026-06-20',
                'title' => 'Scheduled class timeline filters',
                'items' => ['Added timeline filters for generated classes and covered the filtering behavior with feature tests.'],
                'meta' => 'Commit cadc37f.',
            ],
            [
                'version' => '0.9.0',
                'date' => '2026-06-20',
                'title' => 'Scheduled class and slug handling refactor',
                'items' => ['Refined schedule class management, customer search, slug generation, locale handling, and related tests.'],
                'meta' => 'Commit 48ce0d1.',
            ],
            [
                'version' => '0.8.0',
                'date' => '2026-06-20',
                'title' => 'Studio owner navigation',
                'items' => ['Reworked studio owner navigation, brand settings, owner profile entry points, and account-scoped settings flow.'],
                'meta' => 'Commit 0224419.',
            ],
            [
                'version' => '0.7.1',
                'date' => '2026-06-20',
                'title' => 'Unreadable integration credentials recovery',
                'items' => ['Handled saved integration secrets that cannot be decrypted and prompted users to re-enter them safely.'],
                'meta' => 'Commit 078ee51.',
            ],
            [
                'version' => '0.7.0',
                'date' => '2026-06-19',
                'title' => 'Class pass pricing UX',
                'items' => ['Improved class pass pricing controls, validation, any-time add-on behavior, and test coverage.'],
                'meta' => 'Commit a434d1f.',
            ],
            [
                'version' => '0.6.0',
                'date' => '2026-06-19',
                'title' => 'Platform account profile settings',
                'items' => ['Added platform admin profile management and shared profile update handling.'],
                'meta' => 'Commit 54ce3c8.',
            ],
            [
                'version' => '0.5.0',
                'date' => '2026-06-19',
                'title' => 'Owner profile settings and Ladna guidance',
                'items' => ['Added studio owner profile settings and renamed the domain guidance from Charm CRM to Ladna.'],
                'meta' => 'Commit 89d6937.',
            ],
            [
                'version' => '0.4.1',
                'date' => '2026-06-19',
                'title' => 'Sanitized README restored',
                'items' => ['Restored a clean README and adjusted the example environment file.'],
                'meta' => 'Commit f48b3fa.',
            ],
            [
                'version' => '0.4.0',
                'date' => '2026-06-19',
                'title' => 'Ladna repository preparation',
                'items' => ['Prepared the Ladna-branded app shell, system appearance settings, trainer levels, brand assets, and supporting tests.'],
                'meta' => 'Commit e992c68.',
            ],
            [
                'version' => '0.3.0',
                'date' => '2026-06-17',
                'title' => 'Integration settings',
                'items' => ['Added platform and studio integration configuration, provider catalog metadata, and settings tests.'],
                'meta' => 'Commit c3d3865.',
            ],
            [
                'version' => '0.2.0',
                'date' => '2026-06-17',
                'title' => 'CRM domain roles and studio flows',
                'items' => ['Introduced studio roles, permissions, customers, class passes, bookings, trainers, subscriptions, and domain tests.'],
                'meta' => 'Commit ee60fe2.',
            ],
            [
                'version' => '0.1.0',
                'date' => '2026-06-16',
                'title' => 'Initial application baseline',
                'items' => ['Created the Laravel application baseline with Ladna scheduling, accounts, public schedule, tests, local agent guidance, and frontend assets.'],
                'meta' => 'Commit b9f0de6.',
            ],
        ],
        'uk' => [
            [
                'version' => '0.17.0',
                'date' => '2026-06-23',
                'title' => 'Клієнтський вхід і кабінет',
                'items' => ['Додано брендовані сторінки клієнтського входу для студій, налаштування email/password, OTP і Google OAuth, захист Turnstile, 90-денні клієнтські сесії, маски телефону, обовʼязкове доповнення профілю, зміну пароля, QR-посилання для входу та перші екрани клієнтського кабінету з абонементами, відвідуваннями й профілем.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.16.0',
                'date' => '2026-06-21',
                'title' => 'Публічні юридичні сторінки',
                'items' => ['Додано публічні сторінки Угоди користувача та Політики конфіденційності українською й англійською мовами, а також локалізовані посилання у футері для підготовки Google Developer Console.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.15.0',
                'date' => '2026-06-21',
                'title' => 'Production deployment workflow',
                'items' => ['Додано guarded skill для production deploy Ladna з dry-run перевірками, production SSH handoff, встановленням locked залежностей, Vite build, forced migrations без seeders, оптимізацією кешів, restart queue та cleanup maintenance mode.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.14.0',
                'date' => '2026-06-21',
                'title' => 'Життєвий цикл студійних абонементів',
                'items' => [
                    'Додано куплені клієнтські абонементи з унікальними кодами, ledger резервів і відвідувань, ручну видачу, керування активними абонементами, історію в картці клієнта, попередження в записах без відповідного абонемента, команду нормалізації, публічну сторінку цін, embeddable price API та demo-ціни Charmpole для групових занять, індивідуальних занять, оренди й пробних занять.',
                ],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.13.0',
                'date' => '2026-06-20',
                'title' => 'Асинхронне керування записами на заняття',
                'items' => ['Зроблено додавання, зміну статусу й видалення записів у керуванні заняттями без повного перезавантаження сторінки, перенесено старі заняття поточного дня в згортуваний блок історії та додано reusable ajaxable-forms skill для майбутніх форм.'],
                'meta' => 'Релізний коміт.',
            ],
            [
                'version' => '0.12.0',
                'date' => '2026-06-20',
                'title' => 'Основа версіонування та журналу змін',
                'items' => ['Додано кореневий файл VERSION, сторінки журналу змін двома мовами в Laravel, версію у футері та skill для релізного процесу.'],
                'meta' => 'Реліз системи версіонування.',
            ],
            [
                'version' => '0.11.0',
                'date' => '2026-06-20',
                'title' => 'Кольори напрямів у таймлайні занять',
                'items' => ['Додано обробку кольорів напрямів активності та показ цих кольорів у таймлайні занять.'],
                'meta' => 'Коміт a800d35.',
            ],
            [
                'version' => '0.10.1',
                'date' => '2026-06-20',
                'title' => 'Технічне оновлення залежностей',
                'items' => ['Оновлено lockfile після npm audit fix.'],
                'meta' => 'Коміт df51a9a.',
            ],
            [
                'version' => '0.10.0',
                'date' => '2026-06-20',
                'title' => 'Фільтри таймлайна занять',
                'items' => ['Додано фільтри для згенерованих занять і покрито поведінку фільтрації feature-тестами.'],
                'meta' => 'Коміт cadc37f.',
            ],
            [
                'version' => '0.9.0',
                'date' => '2026-06-20',
                'title' => 'Рефакторинг занять і slug-логіки',
                'items' => ['Уточнено керування заняттями, пошук клієнтів, генерацію slug, локаль і повʼязані тести.'],
                'meta' => 'Коміт 48ce0d1.',
            ],
            [
                'version' => '0.8.0',
                'date' => '2026-06-20',
                'title' => 'Навігація власника студії',
                'items' => ['Перероблено навігацію власника студії, налаштування бренду, профіль власника та account-scoped налаштування.'],
                'meta' => 'Коміт 0224419.',
            ],
            [
                'version' => '0.7.1',
                'date' => '2026-06-20',
                'title' => 'Відновлення недоступних інтеграційних даних',
                'items' => ['Оброблено збережені інтеграційні секрети, які неможливо розшифрувати, і додано безпечний запит на повторне введення.'],
                'meta' => 'Коміт 078ee51.',
            ],
            [
                'version' => '0.7.0',
                'date' => '2026-06-19',
                'title' => 'UX цін абонементів',
                'items' => ['Покращено керування цінами абонементів, валідацію, поведінку any-time add-on і тестове покриття.'],
                'meta' => 'Коміт a434d1f.',
            ],
            [
                'version' => '0.6.0',
                'date' => '2026-06-19',
                'title' => 'Профіль адміністратора платформи',
                'items' => ['Додано керування профілем адміністратора платформи та спільну дію оновлення профілю.'],
                'meta' => 'Коміт 54ce3c8.',
            ],
            [
                'version' => '0.5.0',
                'date' => '2026-06-19',
                'title' => 'Профіль власника та Ladna guidance',
                'items' => ['Додано налаштування профілю власника студії та перейменовано доменні інструкції з Charm CRM на Ladna.'],
                'meta' => 'Коміт 89d6937.',
            ],
            [
                'version' => '0.4.1',
                'date' => '2026-06-19',
                'title' => 'Відновлено очищений README',
                'items' => ['Відновлено чистий README та скориговано приклад environment-файлу.'],
                'meta' => 'Коміт f48b3fa.',
            ],
            [
                'version' => '0.4.0',
                'date' => '2026-06-19',
                'title' => 'Підготовка репозиторію Ladna',
                'items' => ['Підготовлено брендований app shell Ladna, системні налаштування вигляду, рівні тренерів, бренд-ресурси та тести.'],
                'meta' => 'Коміт e992c68.',
            ],
            [
                'version' => '0.3.0',
                'date' => '2026-06-17',
                'title' => 'Налаштування інтеграцій',
                'items' => ['Додано налаштування інтеграцій для платформи й студії, каталог провайдерів і тести налаштувань.'],
                'meta' => 'Коміт c3d3865.',
            ],
            [
                'version' => '0.2.0',
                'date' => '2026-06-17',
                'title' => 'CRM ролі та студійні процеси',
                'items' => ['Додано ролі студії, permissions, клієнтів, абонементи, записи, тренерів, тарифи та доменні тести.'],
                'meta' => 'Коміт ee60fe2.',
            ],
            [
                'version' => '0.1.0',
                'date' => '2026-06-16',
                'title' => 'Початкова база застосунку',
                'items' => ['Створено базовий Laravel-застосунок із розкладом Ladna, акаунтами, публічним розкладом, тестами, локальними agent-інструкціями та frontend-ресурсами.'],
                'meta' => 'Коміт b9f0de6.',
            ],
        ],
    ],
];
