<?php

return [
    'aliases' => [
        'accounts' => 'users',
        'arrow-left' => 'arrow-left',
        'bell' => 'bell',
        'building' => 'building-2',
        'calendar' => 'calendar',
        'chevron-down' => 'chevron-down',
        'chevron-right' => 'chevron-right',
        'class-pass-plans' => 'ticket',
        'class-types' => 'circle-dot',
        'close' => 'x',
        'dashboard' => 'layout-dashboard',
        'directions' => 'waypoints',
        'edit' => 'square-pen',
        'external' => 'external-link',
        'generated-classes' => 'clipboard-list',
        'globe' => 'globe',
        'integrations' => 'settings',
        'locations' => 'map-pin',
        'logout' => 'log-out',
        'map-pin' => 'map-pin',
        'menu' => 'menu',
        'plus' => 'plus',
        'rooms' => 'building',
        'schedule' => 'calendar-days',
        'search' => 'search',
        'settings' => 'settings',
        'sparkles' => 'sparkles',
        'trash' => 'trash-2',
        'trainers' => 'user-round',
        'user' => 'user-round',
    ],

    'trainer_types' => [
        'user-round' => 'app.trainer_type_icon_user_round',
        'crown' => 'app.trainer_type_icon_crown',
        'star' => 'app.trainer_type_icon_star',
        'badge-check' => 'app.trainer_type_icon_badge_check',
        'sparkles' => 'app.trainer_type_icon_sparkles',
        'flame' => 'app.trainer_type_icon_flame',
        'heart' => 'app.trainer_type_icon_heart',
        'medal' => 'app.trainer_type_icon_medal',
    ],
];
