@props(['account', 'edition', 'category' => null])
@php($editing = $category?->exists)
<form method="POST" action="{{ $editing ? route('dashboard.accounts.festivals.categories.update', [$account, $edition, $category]) : route('dashboard.accounts.festivals.categories.store', [$account, $edition]) }}" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@csrf @if($editing) @method('PUT') @endif
    <label><span class="crm-label">{{ __('app.code') }}</span><input name="code" value="{{ old('code', $category?->code) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.name') }}</span><input name="name" value="{{ old('name', $category?->name) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.festival_registration_workflow') }}</span><select name="festival_workflow_id" class="crm-field"><option value="">{{ __('app.select') }}</option>@foreach($edition->workflows as $workflow)<option value="{{ $workflow->id }}" @selected((int) old('festival_workflow_id', $category?->festival_workflow_id) === $workflow->id)>{{ $workflow->name }}@unless($workflow->is_active) · {{ __('app.inactive') }}@endunless</option>@endforeach</select></label>
    <label><span class="crm-label">{{ __('app.festival_legacy_review_mode') }}</span><select name="workflow" class="crm-field">@foreach(\App\Enums\FestivalCategoryWorkflow::cases() as $workflow)<option value="{{ $workflow->value }}" @selected(old('workflow', $category?->workflow?->value ?? 'review') === $workflow->value)>{{ __('app.festival_workflow_'.$workflow->value) }}</option>@endforeach</select></label>
    <label><span class="crm-label">{{ __('app.minimum_members') }}</span><input type="number" min="1" max="100" name="min_members" value="{{ old('min_members', $category?->min_members ?? 1) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.maximum_members') }}</span><input type="number" min="1" max="100" name="max_members" value="{{ old('max_members', $category?->max_members ?? 1) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.minimum_age') }}</span><input type="number" min="0" max="100" name="min_age" value="{{ old('min_age', $category?->min_age) }}" class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.maximum_age') }}</span><input type="number" min="0" max="100" name="max_age" value="{{ old('max_age', $category?->max_age) }}" class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.minimum_duration_seconds') }}</span><input type="number" min="1" name="min_duration_seconds" value="{{ old('min_duration_seconds', $category?->min_duration_seconds) }}" class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.maximum_duration_seconds') }}</span><input type="number" min="1" name="max_duration_seconds" value="{{ old('max_duration_seconds', $category?->max_duration_seconds) }}" class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.festival_registration_closes_at') }}</span><input type="datetime-local" name="registration_closes_at" value="{{ old('registration_closes_at', $category?->registration_closes_at?->format('Y-m-d\TH:i')) }}" class="crm-field"></label>
    <div class="flex items-end pb-3"><input type="hidden" name="is_active" value="0"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $category?->is_active ?? true))>{{ __('app.active') }}</label></div>
    <div class="sm:col-span-2 xl:col-span-4"><span class="crm-label">{{ __('app.festival_allowed_classification') }}</span><div class="mt-2 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach($edition->axes as $axis)<fieldset class="rounded-xl border border-stone-200 p-3"><legend class="px-1 text-sm font-semibold">{{ $axis->name }}@unless($axis->is_active) · {{ __('app.inactive') }}@endunless</legend><div class="mt-2 flex flex-wrap gap-3">@foreach($axis->options as $option)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="option_ids[]" value="{{ $option->id }}" @checked(collect(old('option_ids', $category?->options?->modelKeys() ?? []))->contains($option->id))>{{ $option->label }}@unless($option->is_active) · {{ __('app.inactive') }}@endunless</label>@endforeach</div></fieldset>@endforeach</div></div>
    <div class="sm:col-span-2 xl:col-span-4"><x-ui.button type="submit">{{ __('app.save') }}</x-ui.button></div>
</form>
