@props(['account', 'edition', 'fee' => null])
@php($editing = $fee?->exists)
<form method="POST" action="{{ $editing ? route('dashboard.accounts.festivals.charge-definitions.update', [$account, $edition, $fee]) : route('dashboard.accounts.festivals.charge-definitions.store', [$account, $edition]) }}" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@csrf @if($editing) @method('PUT') @endif
    <label><span class="crm-label">{{ __('app.name') }}</span><input name="name" value="{{ old('name', $fee?->name) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.type') }}</span><select name="kind" class="crm-field">@foreach(['qualification', 'participation', 'late', 'custom'] as $kind)<option value="{{ $kind }}" @selected(old('kind', $fee?->kind) === $kind)>{{ __('app.festival_charge_kind_'.$kind) }}</option>@endforeach</select></label>
    <label><span class="crm-label">{{ __('app.amount_cents') }}</span><input type="number" min="0" name="amount_cents" value="{{ old('amount_cents', $fee?->amount_cents) }}" required class="crm-field"></label>
    <label><span class="crm-label">{{ __('app.festival_category') }}</span><select name="festival_category_id" class="crm-field"><option value="">{{ __('app.all') }}</option>@foreach($edition->categories as $category)<option value="{{ $category->id }}" @selected((int) old('festival_category_id', $fee?->festival_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
    <label class="sm:col-span-2"><span class="crm-label">{{ __('app.festival_registration_workflow_step') }}</span><select name="festival_workflow_step_id" required class="crm-field">@foreach($edition->workflows as $workflow)@foreach($workflow->steps as $step)<option value="{{ $step->id }}" @selected((int) old('festival_workflow_step_id', $fee?->festival_workflow_step_id) === $step->id)>{{ $workflow->name }} · {{ $step->title }}</option>@endforeach @endforeach</select></label>
    <label><span class="crm-label">{{ __('app.festival_due_at') }}</span><input type="datetime-local" name="due_at" value="{{ old('due_at', $fee?->due_at?->format('Y-m-d\TH:i')) }}" class="crm-field"></label>
    <div class="flex items-end pb-3"><input type="hidden" name="is_active" value="0"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $fee?->is_active ?? true))>{{ __('app.active') }}</label></div>
    <div class="sm:col-span-2 lg:col-span-4"><x-ui.button type="submit">{{ __('app.save') }}</x-ui.button></div>
</form>
