<?php

use App\Http\Controllers\FestivalAdmissionTypeController;
use App\Http\Controllers\FestivalAnnouncementController;
use App\Http\Controllers\FestivalApplicationDecisionController;
use App\Http\Controllers\FestivalApplicationMediaDuplicateController;
use App\Http\Controllers\FestivalApplicationMediaReportController;
use App\Http\Controllers\FestivalBattleController;
use App\Http\Controllers\FestivalBattleVoteController;
use App\Http\Controllers\FestivalBrandingController;
use App\Http\Controllers\FestivalCategoryController;
use App\Http\Controllers\FestivalChargeDefinitionController;
use App\Http\Controllers\FestivalContentSectionController;
use App\Http\Controllers\FestivalDirectionController;
use App\Http\Controllers\FestivalDocumentController;
use App\Http\Controllers\FestivalEditionPurchaseController;
use App\Http\Controllers\FestivalEntranceController;
use App\Http\Controllers\FestivalEntryStepController;
use App\Http\Controllers\FestivalFileController;
use App\Http\Controllers\FestivalJudgeAssignmentController;
use App\Http\Controllers\FestivalJudgingController;
use App\Http\Controllers\FestivalMediaController;
use App\Http\Controllers\FestivalNominationAssignmentController;
use App\Http\Controllers\FestivalNominationController;
use App\Http\Controllers\FestivalOnlineStreamController;
use App\Http\Controllers\FestivalParticipantPhotoController;
use App\Http\Controllers\FestivalPortalRosterController;
use App\Http\Controllers\FestivalPortalUserController;
use App\Http\Controllers\FestivalRequirementController;
use App\Http\Controllers\FestivalResultController;
use App\Http\Controllers\FestivalResultTableController;
use App\Http\Controllers\FestivalRubricController;
use App\Http\Controllers\FestivalScheduleController;
use App\Http\Controllers\FestivalSeriesController;
use App\Http\Controllers\FestivalSettingsController;
use App\Http\Controllers\FestivalStaffController;
use App\Http\Controllers\FestivalStageController;
use App\Http\Controllers\FestivalTelegramBotController;
use App\Http\Controllers\FestivalTicketIssuanceController;
use App\Http\Controllers\FestivalTicketScannerController;
use App\Http\Controllers\FestivalTimelineController;
use App\Http\Controllers\FestivalWorkflowController;
use App\Http\Controllers\FestivalWorkflowStepController;
use App\Http\Controllers\FestivalWorkspaceController;
use App\Http\Middleware\EnsureFestivalEditionWritable;
use App\Http\Middleware\EnsureFestivalsEnabled;
use Illuminate\Support\Facades\Route;

Route::prefix('accounts/{account}/festivals')->name('accounts.festivals.')->middleware([EnsureFestivalsEnabled::class, EnsureFestivalEditionWritable::class])->scopeBindings()->group(function (): void {
    Route::get('/', [FestivalStaffController::class, 'index'])->name('index');
    Route::post('purchases', [FestivalEditionPurchaseController::class, 'store'])->name('purchases.store');
    Route::get('create', [FestivalStaffController::class, 'create'])->name('create');
    Route::post('/', [FestivalStaffController::class, 'store'])->name('store');
    Route::get('series/create', [FestivalSeriesController::class, 'create'])->name('series.create');
    Route::post('series', [FestivalSeriesController::class, 'store'])->name('series.store');
    Route::get('series/{festivalSeries:id}/edit', [FestivalSeriesController::class, 'edit'])->whereNumber('festivalSeries')->name('series.edit');
    Route::put('series/{festivalSeries:id}', [FestivalSeriesController::class, 'update'])->whereNumber('festivalSeries')->name('series.update');
    Route::put('series/{festivalSeries:id}/telegram-bot', [FestivalTelegramBotController::class, 'update'])->whereNumber('festivalSeries')->name('series.telegram-bot.update');
    Route::post('series/{festivalSeries:id}/telegram-bot/reconnect', [FestivalTelegramBotController::class, 'reconnect'])->whereNumber('festivalSeries')->name('series.telegram-bot.reconnect');
    Route::post('series/{festivalSeries:id}/telegram-bot/check', [FestivalTelegramBotController::class, 'check'])->whereNumber('festivalSeries')->name('series.telegram-bot.check');
    Route::post('series/{festivalSeries:id}/telegram-bot/disable', [FestivalTelegramBotController::class, 'disable'])->whereNumber('festivalSeries')->name('series.telegram-bot.disable');
    Route::delete('series/{festivalSeries:id}/telegram-bot', [FestivalTelegramBotController::class, 'destroy'])->whereNumber('festivalSeries')->name('series.telegram-bot.destroy');
    Route::put('notification-settings', [FestivalAnnouncementController::class, 'updateSettings'])->name('notification-settings.update');
    Route::get('files/submissions/{festivalSubmission}/view', [FestivalFileController::class, 'viewSubmission'])->name('submissions.view');
    Route::get('files/submissions/{festivalSubmission}', [FestivalFileController::class, 'submission'])->name('submissions.download');
    Route::get('{festivalEdition:id}', [FestivalStaffController::class, 'show'])->whereNumber('festivalEdition')->name('show');
    Route::get('{festivalEdition:id}/users', [FestivalPortalUserController::class, 'index'])->whereNumber('festivalEdition')->name('users.index');
    Route::get('{festivalEdition:id}/users/{role}/create', [FestivalPortalUserController::class, 'create'])->whereNumber('festivalEdition')->whereIn('role', ['registrant', 'judge', 'guest'])->name('users.create');
    Route::post('{festivalEdition:id}/users/{role}', [FestivalPortalUserController::class, 'store'])->whereNumber('festivalEdition')->whereIn('role', ['registrant', 'judge', 'guest'])->name('users.store');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/edit', [FestivalPortalUserController::class, 'edit'])->whereNumber('festivalEdition')->name('users.edit');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/team', [FestivalPortalRosterController::class, 'index'])->whereNumber('festivalEdition')->name('users.team');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/notifications', [FestivalPortalUserController::class, 'notifications'])->whereNumber('festivalEdition')->name('users.notifications');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/photo', [FestivalParticipantPhotoController::class, 'staffProfile'])->whereNumber('festivalEdition')->name('users.photo');
    Route::put('{festivalEdition:id}/users/{festivalPortalUser}', [FestivalPortalUserController::class, 'update'])->whereNumber('festivalEdition')->name('users.update');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/participants/create', [FestivalPortalRosterController::class, 'create'])->whereNumber('festivalEdition')->name('users.participants.create');
    Route::post('{festivalEdition:id}/users/{festivalPortalUser}/participants', [FestivalPortalRosterController::class, 'store'])->whereNumber('festivalEdition')->name('users.participants.store');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/participants/{festivalParticipant}/edit', [FestivalPortalRosterController::class, 'edit'])->whereNumber('festivalEdition')->name('users.participants.edit');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/participants/{festivalParticipant}/photo', [FestivalParticipantPhotoController::class, 'staffParticipant'])->whereNumber('festivalEdition')->name('users.participants.photo');
    Route::put('{festivalEdition:id}/users/{festivalPortalUser}/participants/{festivalParticipant}', [FestivalPortalRosterController::class, 'update'])->whereNumber('festivalEdition')->name('users.participants.update');
    Route::get('{festivalEdition:id}/users/{festivalPortalUser}/participants/{festivalParticipant}/archive', [FestivalPortalRosterController::class, 'archive'])->whereNumber('festivalEdition')->name('users.participants.archive');
    Route::patch('{festivalEdition:id}/users/{festivalPortalUser}/participants/{festivalParticipant}/archive', [FestivalPortalRosterController::class, 'destroy'])->whereNumber('festivalEdition')->name('users.participants.destroy');
    Route::get('{festivalEdition:id}/applications', [FestivalWorkspaceController::class, 'applications'])->whereNumber('festivalEdition')->name('applications');
    Route::get('{festivalEdition:id}/applications/media-report', FestivalApplicationMediaReportController::class)->whereNumber('festivalEdition')->name('applications.media-report');
    Route::post('{festivalEdition:id}/applications/media-report/duplicates', FestivalApplicationMediaDuplicateController::class)->whereNumber('festivalEdition')->name('applications.media-report.duplicates');
    Route::get('{festivalEdition:id}/applications/{festivalEntry}', [FestivalWorkspaceController::class, 'application'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('applications.show');
    Route::get('{festivalEdition:id}/applications/{festivalEntry}/history', [FestivalWorkspaceController::class, 'applicationHistory'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('applications.history');
    Route::patch('{festivalEdition:id}/applications/{festivalEntry}/fully-confirm', [FestivalApplicationDecisionController::class, 'confirm'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('applications.fully-confirm');
    Route::patch('{festivalEdition:id}/applications/{festivalEntry}/fully-decline', [FestivalApplicationDecisionController::class, 'decline'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('applications.fully-decline');
    Route::delete('{festivalEdition:id}/applications/{festivalEntry}', [FestivalWorkspaceController::class, 'destroyApplication'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('applications.destroy');
    Route::get('{festivalEdition:id}/performances', [FestivalWorkspaceController::class, 'performances'])->whereNumber('festivalEdition')->name('performances');
    Route::get('{festivalEdition:id}/performances/{festivalEntry}', [FestivalWorkspaceController::class, 'performance'])->whereNumber('festivalEdition')->whereNumber('festivalEntry')->name('performances.show');
    Route::get('{festivalEdition:id}/program', [FestivalWorkspaceController::class, 'program'])->whereNumber('festivalEdition')->name('program');
    Route::get('{festivalEdition:id}/timeline', [FestivalTimelineController::class, 'index'])->whereNumber('festivalEdition')->name('timeline.index');
    Route::get('{festivalEdition:id}/timeline/scenes/{festivalStage}', [FestivalTimelineController::class, 'show'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('timeline.show');
    Route::get('{festivalEdition:id}/timeline/scenes/{festivalStage}/fragment', [FestivalTimelineController::class, 'fragment'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('timeline.fragment');
    Route::get('{festivalEdition:id}/tickets', [FestivalWorkspaceController::class, 'tickets'])->whereNumber('festivalEdition')->name('tickets');
    Route::get('{festivalEdition:id}/tickets/issue', [FestivalTicketIssuanceController::class, 'create'])->whereNumber('festivalEdition')->name('tickets.issue');
    Route::get('{festivalEdition:id}/online-stream', [FestivalOnlineStreamController::class, 'edit'])->whereNumber('festivalEdition')->name('online-stream.edit');
    Route::get('{festivalEdition:id}/online-stream/status', [FestivalOnlineStreamController::class, 'status'])->whereNumber('festivalEdition')->middleware('throttle:festival-stream-status')->name('online-stream.status');
    Route::get('{festivalEdition:id}/online-stream/preview', [FestivalOnlineStreamController::class, 'preview'])->whereNumber('festivalEdition')->middleware('throttle:festival-stream-bootstrap')->name('online-stream.preview');
    Route::get('{festivalEdition:id}/admission-types/create', [FestivalAdmissionTypeController::class, 'create'])->whereNumber('festivalEdition')->name('admission-types.create');
    Route::get('{festivalEdition:id}/admission-types/{festivalAdmissionType}/edit', [FestivalAdmissionTypeController::class, 'edit'])->whereNumber('festivalEdition')->whereNumber('festivalAdmissionType')->name('admission-types.edit');
    Route::get('{festivalEdition:id}/communication', [FestivalWorkspaceController::class, 'communication'])->whereNumber('festivalEdition')->name('communication');
    Route::get('{festivalEdition:id}/communication/history', [FestivalWorkspaceController::class, 'communicationHistory'])->whereNumber('festivalEdition')->name('communication.history');
    Route::get('{festivalEdition:id}/communication/announcements', [FestivalWorkspaceController::class, 'communicationAnnouncements'])->whereNumber('festivalEdition')->name('communication.announcements');
    Route::get('{festivalEdition:id}/communication/settings', [FestivalWorkspaceController::class, 'communicationSettings'])->whereNumber('festivalEdition')->name('communication.settings');
    Route::get('{festivalEdition:id}/settings', [FestivalSettingsController::class, 'overview'])->whereNumber('festivalEdition')->name('settings');
    Route::get('{festivalEdition:id}/settings/scenes', [FestivalStageController::class, 'index'])->whereNumber('festivalEdition')->name('settings.stages');
    Route::get('{festivalEdition:id}/settings/scenes/create', [FestivalStageController::class, 'create'])->whereNumber('festivalEdition')->name('stages.create');
    Route::get('{festivalEdition:id}/settings/scenes/{festivalStage}/edit', [FestivalStageController::class, 'edit'])->whereNumber('festivalEdition')->name('stages.edit');
    Route::get('{festivalEdition:id}/settings/directions', [FestivalDirectionController::class, 'index'])->whereNumber('festivalEdition')->name('settings.directions');
    Route::get('{festivalEdition:id}/settings/directions/create', [FestivalDirectionController::class, 'create'])->whereNumber('festivalEdition')->name('directions.create');
    Route::get('{festivalEdition:id}/settings/directions/{festivalDirection}/edit', [FestivalDirectionController::class, 'edit'])->whereNumber('festivalEdition')->name('directions.edit');
    Route::get('{festivalEdition:id}/settings/nominations', [FestivalNominationController::class, 'index'])->whereNumber('festivalEdition')->name('settings.nominations');
    Route::get('{festivalEdition:id}/settings/nominations/create', [FestivalNominationController::class, 'create'])->whereNumber('festivalEdition')->name('nominations.create');
    Route::get('{festivalEdition:id}/settings/nominations/{festivalNomination}/edit', [FestivalNominationController::class, 'edit'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('nominations.edit');
    Route::get('{festivalEdition:id}/settings/categories', [FestivalCategoryController::class, 'index'])->whereNumber('festivalEdition')->name('settings.categories');
    Route::get('{festivalEdition:id}/settings/categories/create', [FestivalCategoryController::class, 'create'])->whereNumber('festivalEdition')->name('categories.create');
    Route::get('{festivalEdition:id}/settings/categories/{festivalCategory}/edit', [FestivalCategoryController::class, 'edit'])->whereNumber('festivalEdition')->name('categories.edit');
    Route::get('{festivalEdition:id}/settings/workflows', [FestivalWorkflowController::class, 'index'])->whereNumber('festivalEdition')->name('settings.workflows');
    Route::get('{festivalEdition:id}/settings/workflows/create', [FestivalWorkflowController::class, 'create'])->whereNumber('festivalEdition')->name('workflows.create');
    Route::get('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/edit', [FestivalWorkflowController::class, 'edit'])->whereNumber('festivalEdition')->name('workflows.edit');
    Route::get('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps', [FestivalWorkflowStepController::class, 'index'])->whereNumber('festivalEdition')->name('workflow-steps.index');
    Route::get('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/create', [FestivalWorkflowStepController::class, 'create'])->whereNumber('festivalEdition')->name('workflow-steps.create');
    Route::get('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/{festivalWorkflowStep}/edit', [FestivalWorkflowStepController::class, 'edit'])->whereNumber('festivalEdition')->name('workflow-steps.edit');
    Route::get('{festivalEdition:id}/settings/requirements', [FestivalRequirementController::class, 'index'])->whereNumber('festivalEdition')->name('settings.requirements');
    Route::get('{festivalEdition:id}/settings/requirements/create', [FestivalRequirementController::class, 'create'])->whereNumber('festivalEdition')->name('requirements.create');
    Route::get('{festivalEdition:id}/settings/requirements/{festivalRequirementDefinition}/edit', [FestivalRequirementController::class, 'edit'])->whereNumber('festivalEdition')->name('requirements.edit');
    Route::get('{festivalEdition:id}/settings/fees', [FestivalChargeDefinitionController::class, 'index'])->whereNumber('festivalEdition')->name('settings.fees');
    Route::get('{festivalEdition:id}/settings/fees/create', [FestivalChargeDefinitionController::class, 'create'])->whereNumber('festivalEdition')->name('charge-definitions.create');
    Route::get('{festivalEdition:id}/settings/fees/{festivalChargeDefinition}/edit', [FestivalChargeDefinitionController::class, 'edit'])->whereNumber('festivalEdition')->name('charge-definitions.edit');
    Route::get('{festivalEdition:id}/settings/content', [FestivalSettingsController::class, 'content'])->whereNumber('festivalEdition')->name('settings.content');
    Route::get('{festivalEdition:id}/settings/content/sections', [FestivalContentSectionController::class, 'index'])->whereNumber('festivalEdition')->name('settings.content.sections');
    Route::get('{festivalEdition:id}/settings/content/sections/create', [FestivalContentSectionController::class, 'create'])->whereNumber('festivalEdition')->name('content.create');
    Route::get('{festivalEdition:id}/settings/content/sections/{festivalContentSection}/edit', [FestivalContentSectionController::class, 'edit'])->whereNumber('festivalEdition')->name('content.edit');
    Route::get('{festivalEdition:id}/settings/content/documents', [FestivalDocumentController::class, 'index'])->whereNumber('festivalEdition')->name('settings.content.documents');
    Route::get('{festivalEdition:id}/settings/content/documents/create', [FestivalDocumentController::class, 'create'])->whereNumber('festivalEdition')->name('documents.create');
    Route::get('{festivalEdition:id}/settings/content/documents/{festivalDocument}/edit', [FestivalDocumentController::class, 'edit'])->whereNumber('festivalEdition')->name('documents.edit');
    Route::get('{festivalEdition:id}/settings/content/media', [FestivalMediaController::class, 'index'])->whereNumber('festivalEdition')->name('settings.content.media');
    Route::get('{festivalEdition:id}/settings/content/media/create', [FestivalMediaController::class, 'create'])->whereNumber('festivalEdition')->name('media.create');
    Route::get('{festivalEdition:id}/settings/content/media/{festivalMedia}/edit', [FestivalMediaController::class, 'edit'])->whereNumber('festivalEdition')->name('media.edit');
    Route::get('{festivalEdition:id}/edit', [FestivalStaffController::class, 'edit'])->whereNumber('festivalEdition')->name('edit');
    Route::put('{festivalEdition:id}', [FestivalStaffController::class, 'update'])->whereNumber('festivalEdition')->name('update');
    Route::put('{festivalEdition:id}/branding', [FestivalBrandingController::class, 'update'])->whereNumber('festivalEdition')->name('branding.update');
    Route::post('{festivalEdition:id}/directions', [FestivalDirectionController::class, 'store'])->whereNumber('festivalEdition')->name('directions.store');
    Route::put('{festivalEdition:id}/settings/directions/{festivalDirection}', [FestivalDirectionController::class, 'update'])->whereNumber('festivalEdition')->name('directions.update');
    Route::patch('{festivalEdition:id}/settings/directions/{festivalDirection}/toggle', [FestivalDirectionController::class, 'toggle'])->whereNumber('festivalEdition')->name('directions.toggle');
    Route::patch('{festivalEdition:id}/settings/directions/{festivalDirection}/move', [FestivalDirectionController::class, 'move'])->whereNumber('festivalEdition')->name('directions.move');
    Route::post('{festivalEdition:id}/nominations', [FestivalNominationController::class, 'store'])->whereNumber('festivalEdition')->name('nominations.store');
    Route::put('{festivalEdition:id}/settings/nominations/{festivalNomination}', [FestivalNominationController::class, 'update'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('nominations.update');
    Route::patch('{festivalEdition:id}/settings/nominations/{festivalNomination}/toggle', [FestivalNominationController::class, 'toggle'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('nominations.toggle');
    Route::patch('{festivalEdition:id}/settings/nominations/{festivalNomination}/move', [FestivalNominationController::class, 'move'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('nominations.move');
    Route::delete('{festivalEdition:id}/settings/nominations/{festivalNomination}', [FestivalNominationController::class, 'destroy'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('nominations.destroy');
    Route::post('{festivalEdition:id}/categories', [FestivalCategoryController::class, 'store'])->whereNumber('festivalEdition')->name('categories.store');
    Route::put('{festivalEdition:id}/settings/categories/{festivalCategory}', [FestivalCategoryController::class, 'update'])->whereNumber('festivalEdition')->name('categories.update');
    Route::patch('{festivalEdition:id}/settings/categories/{festivalCategory}/toggle', [FestivalCategoryController::class, 'toggle'])->whereNumber('festivalEdition')->name('categories.toggle');
    Route::patch('{festivalEdition:id}/settings/categories/{festivalCategory}/move', [FestivalCategoryController::class, 'move'])->whereNumber('festivalEdition')->name('categories.move');
    Route::post('{festivalEdition:id}/content', [FestivalContentSectionController::class, 'store'])->whereNumber('festivalEdition')->name('content.store');
    Route::put('{festivalEdition:id}/settings/content/{festivalContentSection}', [FestivalContentSectionController::class, 'update'])->whereNumber('festivalEdition')->name('content.update');
    Route::patch('{festivalEdition:id}/settings/content/{festivalContentSection}/toggle', [FestivalContentSectionController::class, 'toggle'])->whereNumber('festivalEdition')->name('content.toggle');
    Route::patch('{festivalEdition:id}/settings/content/{festivalContentSection}/move', [FestivalContentSectionController::class, 'move'])->whereNumber('festivalEdition')->name('content.move');
    Route::delete('{festivalEdition:id}/settings/content/{festivalContentSection}', [FestivalContentSectionController::class, 'destroy'])->whereNumber('festivalEdition')->name('content.destroy');
    Route::post('{festivalEdition:id}/documents', [FestivalDocumentController::class, 'store'])->whereNumber('festivalEdition')->name('documents.store');
    Route::put('{festivalEdition:id}/settings/documents/{festivalDocument}', [FestivalDocumentController::class, 'update'])->whereNumber('festivalEdition')->name('documents.update');
    Route::patch('{festivalEdition:id}/settings/documents/{festivalDocument}/toggle', [FestivalDocumentController::class, 'toggle'])->whereNumber('festivalEdition')->name('documents.toggle');
    Route::patch('{festivalEdition:id}/settings/documents/{festivalDocument}/move', [FestivalDocumentController::class, 'move'])->whereNumber('festivalEdition')->name('documents.move');
    Route::post('{festivalEdition:id}/media', [FestivalMediaController::class, 'store'])->whereNumber('festivalEdition')->name('media.store');
    Route::put('{festivalEdition:id}/settings/media/{festivalMedia}', [FestivalMediaController::class, 'update'])->whereNumber('festivalEdition')->name('media.update');
    Route::patch('{festivalEdition:id}/settings/media/{festivalMedia}/toggle', [FestivalMediaController::class, 'toggle'])->whereNumber('festivalEdition')->name('media.toggle');
    Route::patch('{festivalEdition:id}/settings/media/{festivalMedia}/move', [FestivalMediaController::class, 'move'])->whereNumber('festivalEdition')->name('media.move');
    Route::post('{festivalEdition:id}/requirements', [FestivalRequirementController::class, 'store'])->whereNumber('festivalEdition')->name('requirements.store');
    Route::put('{festivalEdition:id}/settings/requirements/{festivalRequirementDefinition}', [FestivalRequirementController::class, 'update'])->whereNumber('festivalEdition')->name('requirements.update');
    Route::patch('{festivalEdition:id}/settings/requirements/{festivalRequirementDefinition}/toggle', [FestivalRequirementController::class, 'toggle'])->whereNumber('festivalEdition')->name('requirements.toggle');
    Route::patch('{festivalEdition:id}/settings/requirements/{festivalRequirementDefinition}/move', [FestivalRequirementController::class, 'move'])->whereNumber('festivalEdition')->name('requirements.move');
    Route::delete('{festivalEdition:id}/settings/requirements/{festivalRequirementDefinition}', [FestivalRequirementController::class, 'destroy'])->whereNumber('festivalEdition')->name('requirements.destroy');
    Route::post('{festivalEdition:id}/charge-definitions', [FestivalChargeDefinitionController::class, 'store'])->whereNumber('festivalEdition')->name('charge-definitions.store');
    Route::put('{festivalEdition:id}/settings/charge-definitions/{festivalChargeDefinition}', [FestivalChargeDefinitionController::class, 'update'])->whereNumber('festivalEdition')->name('charge-definitions.update');
    Route::patch('{festivalEdition:id}/settings/charge-definitions/{festivalChargeDefinition}/toggle', [FestivalChargeDefinitionController::class, 'toggle'])->whereNumber('festivalEdition')->name('charge-definitions.toggle');
    Route::patch('{festivalEdition:id}/settings/charge-definitions/{festivalChargeDefinition}/move', [FestivalChargeDefinitionController::class, 'move'])->whereNumber('festivalEdition')->name('charge-definitions.move');
    Route::post('{festivalEdition:id}/workflows', [FestivalWorkflowController::class, 'store'])->whereNumber('festivalEdition')->name('workflows.store');
    Route::put('{festivalEdition:id}/settings/workflows/{festivalWorkflow}', [FestivalWorkflowController::class, 'update'])->whereNumber('festivalEdition')->name('workflows.update');
    Route::patch('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/toggle', [FestivalWorkflowController::class, 'toggle'])->whereNumber('festivalEdition')->name('workflows.toggle');
    Route::patch('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/move', [FestivalWorkflowController::class, 'move'])->whereNumber('festivalEdition')->name('workflows.move');
    Route::post('{festivalEdition:id}/workflows/{festivalWorkflow}/steps', [FestivalWorkflowStepController::class, 'store'])->whereNumber('festivalEdition')->name('workflow-steps.store');
    Route::put('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/{festivalWorkflowStep}', [FestivalWorkflowStepController::class, 'update'])->whereNumber('festivalEdition')->name('workflow-steps.update');
    Route::patch('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/{festivalWorkflowStep}/toggle', [FestivalWorkflowStepController::class, 'toggle'])->whereNumber('festivalEdition')->name('workflow-steps.toggle');
    Route::patch('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/{festivalWorkflowStep}/move', [FestivalWorkflowStepController::class, 'move'])->whereNumber('festivalEdition')->name('workflow-steps.move');
    Route::delete('{festivalEdition:id}/settings/workflows/{festivalWorkflow}/steps/{festivalWorkflowStep}', [FestivalWorkflowStepController::class, 'destroy'])->whereNumber('festivalEdition')->name('workflow-steps.destroy');
    Route::post('{festivalEdition:id}/settings/scenes', [FestivalStageController::class, 'store'])->whereNumber('festivalEdition')->name('stages.store');
    Route::put('{festivalEdition:id}/settings/scenes/{festivalStage}', [FestivalStageController::class, 'update'])->whereNumber('festivalEdition')->name('stages.update');
    Route::patch('{festivalEdition:id}/settings/scenes/{festivalStage}/toggle', [FestivalStageController::class, 'toggle'])->whereNumber('festivalEdition')->name('stages.toggle');
    Route::patch('{festivalEdition:id}/settings/scenes/{festivalStage}/move', [FestivalStageController::class, 'move'])->whereNumber('festivalEdition')->name('stages.move');
    Route::post('{festivalEdition:id}/admission-types', [FestivalAdmissionTypeController::class, 'store'])->whereNumber('festivalEdition')->name('admission-types.store');
    Route::put('{festivalEdition:id}/admission-types/{festivalAdmissionType}', [FestivalAdmissionTypeController::class, 'update'])->whereNumber('festivalEdition')->whereNumber('festivalAdmissionType')->name('admission-types.update');
    Route::delete('{festivalEdition:id}/admission-types/{festivalAdmissionType}', [FestivalAdmissionTypeController::class, 'destroy'])->whereNumber('festivalEdition')->whereNumber('festivalAdmissionType')->name('admission-types.destroy');
    Route::put('{festivalEdition:id}/online-stream', [FestivalOnlineStreamController::class, 'update'])->whereNumber('festivalEdition')->name('online-stream.update');
    Route::patch('{festivalEdition:id}/online-stream/start', [FestivalOnlineStreamController::class, 'start'])->whereNumber('festivalEdition')->name('online-stream.start');
    Route::patch('{festivalEdition:id}/online-stream/stop', [FestivalOnlineStreamController::class, 'stop'])->whereNumber('festivalEdition')->name('online-stream.stop');
    Route::delete('{festivalEdition:id}/online-stream/leases', [FestivalOnlineStreamController::class, 'resetLeases'])->whereNumber('festivalEdition')->name('online-stream.reset-leases');
    Route::post('{festivalEdition:id}/ticket-orders/{festivalTicketOrder}/refund', [FestivalWorkspaceController::class, 'refundTicketOrder'])->whereNumber('festivalEdition')->whereNumber('festivalTicketOrder')->name('ticket-orders.refund');
    Route::post('{festivalEdition:id}/tickets/issue', [FestivalTicketIssuanceController::class, 'store'])->whereNumber('festivalEdition')->name('tickets.issue.store');
    Route::post('{festivalEdition:id}/tickets/issue/audience', [FestivalTicketIssuanceController::class, 'storeAudience'])->whereNumber('festivalEdition')->name('tickets.issue.audience');
    Route::post('{festivalEdition:id}/tickets/{festivalTicket}/void', [FestivalWorkspaceController::class, 'voidTicket'])->whereNumber('festivalEdition')->whereNumber('festivalTicket')->name('tickets.void');
    Route::patch('{festivalEdition:id}/entries/{festivalEntry}/review', [FestivalStaffController::class, 'reviewEntry'])->whereNumber('festivalEdition')->name('entries.review');
    Route::patch('{festivalEdition:id}/entries/{festivalEntry}/category', [FestivalEntryStepController::class, 'reassignCategory'])->whereNumber('festivalEdition')->name('entries.reassign-category');
    Route::patch('{festivalEdition:id}/entries/{festivalEntry}/steps/{festivalEntryStep}/review', [FestivalEntryStepController::class, 'review'])->whereNumber('festivalEdition')->name('entry-steps.review');
    Route::patch('{festivalEdition:id}/requirements/{festivalEntryRequirement}/review', [FestivalStaffController::class, 'reviewRequirement'])->whereNumber('festivalEdition')->name('requirements.review');
    Route::patch('{festivalEdition:id}/charges/{festivalCharge}/manual-review', [FestivalStaffController::class, 'approveManualCharge'])->whereNumber('festivalEdition')->name('charges.manual-review');
    Route::post('{festivalEdition:id}/schedule', [FestivalScheduleController::class, 'store'])->whereNumber('festivalEdition')->name('schedule.store');
    Route::put('{festivalEdition:id}/schedule/{festivalScheduleSlot}', [FestivalScheduleController::class, 'update'])->whereNumber('festivalEdition')->name('schedule.update');
    Route::post('{festivalEdition:id}/program/scenes/{festivalStage}/generate', [FestivalScheduleController::class, 'generate'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('schedule.generate');
    Route::patch('{festivalEdition:id}/program/scenes/{festivalStage}/order', [FestivalScheduleController::class, 'reorder'])->whereNumber('festivalEdition')->name('schedule.reorder');
    Route::post('{festivalEdition:id}/timeline/fill', [FestivalTimelineController::class, 'fill'])->whereNumber('festivalEdition')->name('timeline.fill');
    Route::post('{festivalEdition:id}/timeline/start', [FestivalTimelineController::class, 'start'])->whereNumber('festivalEdition')->name('timeline.start');
    Route::patch('{festivalEdition:id}/timeline/scenes/{festivalStage}/pause', [FestivalTimelineController::class, 'pause'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('timeline.pause');
    Route::patch('{festivalEdition:id}/timeline/scenes/{festivalStage}/resume', [FestivalTimelineController::class, 'resume'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('timeline.resume');
    Route::patch('{festivalEdition:id}/timeline/scenes/{festivalStage}/order', [FestivalTimelineController::class, 'reorder'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->name('timeline.reorder');
    Route::patch('{festivalEdition:id}/timeline/scenes/{festivalStage}/items/{festivalTimelineItem}/activate', [FestivalTimelineController::class, 'activate'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->whereNumber('festivalTimelineItem')->name('timeline.activate');
    Route::patch('{festivalEdition:id}/timeline/scenes/{festivalStage}/items/{festivalTimelineItem}/toggle', [FestivalTimelineController::class, 'toggle'])->whereNumber('festivalEdition')->whereNumber('festivalStage')->whereNumber('festivalTimelineItem')->name('timeline.toggle');
    Route::get('{festivalEdition:id}/judging', [FestivalJudgingController::class, 'index'])->whereNumber('festivalEdition')->name('judging.index');
    Route::get('{festivalEdition:id}/judging/judges', [FestivalJudgeAssignmentController::class, 'index'])->whereNumber('festivalEdition')->name('judging.judges.index');
    Route::get('{festivalEdition:id}/judging/judges/create', [FestivalJudgeAssignmentController::class, 'create'])->whereNumber('festivalEdition')->name('judging.judges.create');
    Route::post('{festivalEdition:id}/judging/judges', [FestivalJudgeAssignmentController::class, 'store'])->whereNumber('festivalEdition')->name('judging.judges.store');
    Route::get('{festivalEdition:id}/judging/judges/{festivalJudgeAssignment}/edit', [FestivalJudgeAssignmentController::class, 'edit'])->whereNumber('festivalEdition')->name('judging.judges.edit');
    Route::put('{festivalEdition:id}/judging/judges/{festivalJudgeAssignment}', [FestivalJudgeAssignmentController::class, 'update'])->whereNumber('festivalEdition')->name('judging.judges.update');
    Route::patch('{festivalEdition:id}/judging/judges/{festivalJudgeAssignment}/toggle', [FestivalJudgeAssignmentController::class, 'toggle'])->whereNumber('festivalEdition')->name('judging.judges.toggle');
    Route::get('{festivalEdition:id}/judging/criteria', [FestivalRubricController::class, 'index'])->whereNumber('festivalEdition')->name('judging.criteria.index');
    Route::get('{festivalEdition:id}/judging/criteria/create', [FestivalRubricController::class, 'create'])->whereNumber('festivalEdition')->name('judging.criteria.create');
    Route::post('{festivalEdition:id}/judging/criteria', [FestivalRubricController::class, 'store'])->whereNumber('festivalEdition')->name('judging.criteria.store');
    Route::get('{festivalEdition:id}/judging/criteria/{festivalRubric}/edit', [FestivalRubricController::class, 'edit'])->whereNumber('festivalEdition')->name('judging.criteria.edit');
    Route::put('{festivalEdition:id}/judging/criteria/{festivalRubric}', [FestivalRubricController::class, 'update'])->whereNumber('festivalEdition')->name('judging.criteria.update');
    Route::delete('{festivalEdition:id}/judging/criteria/{festivalRubric}', [FestivalRubricController::class, 'destroy'])->whereNumber('festivalEdition')->name('judging.criteria.destroy');
    Route::patch('{festivalEdition:id}/judging/criteria/{festivalRubric}/toggle', [FestivalRubricController::class, 'toggle'])->whereNumber('festivalEdition')->name('judging.criteria.toggle');
    Route::patch('{festivalEdition:id}/judging/criteria/{festivalRubric}/move', [FestivalRubricController::class, 'move'])->whereNumber('festivalEdition')->name('judging.criteria.move');
    Route::get('{festivalEdition:id}/judging/score-sheets', [FestivalJudgingController::class, 'scoreSheets'])->whereNumber('festivalEdition')->name('judging.score-sheets.index');
    Route::post('{festivalEdition:id}/judging/score-sheets/prepare', [FestivalJudgingController::class, 'prepareSheets'])->whereNumber('festivalEdition')->name('judging.score-sheets.prepare');
    Route::get('{festivalEdition:id}/judging/score-sheets/{festivalScoreSheet}/participants/{festivalParticipant}/photo', [FestivalParticipantPhotoController::class, 'judgeStaff'])->whereNumber('festivalEdition')->whereNumber('festivalScoreSheet')->whereNumber('festivalParticipant')->withoutScopedBindings()->name('judging.score-sheets.participants.photo');
    Route::get('{festivalEdition:id}/judging/score-sheets/{festivalScoreSheet}/edit', [FestivalJudgingController::class, 'editStaff'])->whereNumber('festivalEdition')->name('judging.score-sheets.edit');
    Route::put('{festivalEdition:id}/judging/score-sheets/{festivalScoreSheet}', [FestivalJudgingController::class, 'updateStaff'])->whereNumber('festivalEdition')->name('judging.score-sheets.update');
    Route::get('{festivalEdition:id}/judging/results', [FestivalResultController::class, 'index'])->whereNumber('festivalEdition')->name('judging.results.index');
    Route::get('{festivalEdition:id}/judging/results/nominations', [FestivalNominationAssignmentController::class, 'indexStaff'])->whereNumber('festivalEdition')->name('judging.results.nominations.index');
    Route::put('{festivalEdition:id}/judging/results/nominations/{festivalNomination}', [FestivalNominationAssignmentController::class, 'updateStaff'])->whereNumber('festivalEdition')->whereNumber('festivalNomination')->name('judging.results.nominations.update');
    Route::get('{festivalEdition:id}/judging/results/{festivalCategory}/table', [FestivalResultTableController::class, 'showStaff'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->name('judging.results.table');
    Route::put('{festivalEdition:id}/judging/results/{festivalCategory}/table/score-sheets/{festivalScoreSheet}', [FestivalResultTableController::class, 'updateScoreStaff'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->whereNumber('festivalScoreSheet')->withoutScopedBindings()->name('judging.results.table.score-sheets.update');
    Route::post('{festivalEdition:id}/judging/results/{festivalCategory}/table/penalties', [FestivalResultTableController::class, 'storePenaltyStaff'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->name('judging.results.table.penalties.store');
    Route::put('{festivalEdition:id}/judging/results/{festivalCategory}/table/penalties/{festivalPenalty}', [FestivalResultTableController::class, 'updatePenaltyStaff'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->whereNumber('festivalPenalty')->withoutScopedBindings()->name('judging.results.table.penalties.update');
    Route::delete('{festivalEdition:id}/judging/results/{festivalCategory}/table/penalties/{festivalPenalty}', [FestivalResultTableController::class, 'destroyPenaltyStaff'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->whereNumber('festivalPenalty')->withoutScopedBindings()->name('judging.results.table.penalties.destroy');
    Route::get('{festivalEdition:id}/judging/results/{festivalCategory}', [FestivalResultController::class, 'show'])->whereNumber('festivalEdition')->whereNumber('festivalCategory')->name('judging.results.show');
    Route::get('{festivalEdition:id}/judging/battles', [FestivalBattleController::class, 'index'])->whereNumber('festivalEdition')->name('judging.battles.index');
    Route::post('{festivalEdition:id}/judging/battles/{festivalCategory}/generate', [FestivalBattleController::class, 'generate'])->whereNumber('festivalEdition')->name('judging.battles.generate');
    Route::post('{festivalEdition:id}/judging/battles/matches/{festivalBattleMatch}/finalize', [FestivalBattleController::class, 'finalize'])->whereNumber('festivalEdition')->name('judging.battles.finalize');
    Route::get('{festivalEdition:id}/judging/battle-votes', [FestivalBattleVoteController::class, 'indexStaff'])->whereNumber('festivalEdition')->name('judging.battle-votes.index');
    Route::put('{festivalEdition:id}/judging/battle-votes/{festivalBattleMatch}', [FestivalBattleVoteController::class, 'storeStaff'])->whereNumber('festivalEdition')->name('judging.battle-votes.update');
    Route::get('{festivalEdition:id}/score-sheets/{festivalScoreSheet}', [FestivalJudgingController::class, 'legacyEditStaff'])->whereNumber('festivalEdition')->name('score-sheets.edit');
    Route::post('{festivalEdition:id}/announcements', [FestivalAnnouncementController::class, 'store'])->whereNumber('festivalEdition')->name('announcements.store');
    Route::get('{festivalEdition:id}/scanner', [FestivalTicketScannerController::class, 'show'])->whereNumber('festivalEdition')->name('scanner');
    Route::post('{festivalEdition:id}/scanner/scan', [FestivalTicketScannerController::class, 'scan'])->whereNumber('festivalEdition')->middleware('throttle:festival-scanner')->name('scanner.scan');
    Route::get('{festivalEdition:id}/attendance', [FestivalEntranceController::class, 'attendance'])->whereNumber('festivalEdition')->name('attendance');
    Route::get('{festivalEdition:id}/attendance/data', [FestivalEntranceController::class, 'attendanceData'])->whereNumber('festivalEdition')->name('attendance.data');
    Route::post('{festivalEdition:id}/attendance/tickets/{festivalTicket}/undo', [FestivalEntranceController::class, 'undo'])->whereNumber('festivalEdition')->whereNumber('festivalTicket')->middleware('throttle:festival-scanner')->name('attendance.tickets.undo');
    Route::post('{festivalEdition:id}/attendance/passes/{festivalEntrancePass}/undo', [FestivalEntranceController::class, 'undoPass'])->whereNumber('festivalEdition')->whereNumber('festivalEntrancePass')->middleware('throttle:festival-scanner')->name('attendance.passes.undo');
    Route::get('{festivalEdition:id}/entrance/search', [FestivalEntranceController::class, 'search'])->whereNumber('festivalEdition')->middleware('throttle:120,1')->name('entrance.search');
    Route::post('{festivalEdition:id}/entrance/tickets/cash', [FestivalEntranceController::class, 'cashSale'])->whereNumber('festivalEdition')->middleware('throttle:festival-checkout')->name('entrance.cash');
    Route::post('{festivalEdition:id}/entrance/tickets/card', [FestivalEntranceController::class, 'cardSale'])->whereNumber('festivalEdition')->middleware('throttle:festival-checkout')->name('entrance.card');
    Route::get('{festivalEdition:id}/entrance/poster', [FestivalEntranceController::class, 'poster'])->whereNumber('festivalEdition')->name('entrance.poster');
});
